# Generated by Django 3.0.4 on 2020-04-29 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='fecha',
            new_name='date',
        ),
    ]
